### ISSUE TITLE
login and logout functionality

### ISSUE THREAD

**Issue by nrenner0211** [nrenner0211/password-manager#8]
Login/logout functionality are up for grabs. Based on the modules, I put the login.js and logout.js files in public/javascript

**Comment by Akidane47** [comment]
Could I also work on this?

**Comment by Davon95** [comment]
Sorry man, you can't, this is a group project for a bootcamp we're doing.

**Comment by Akidane47** [comment]
I’m sorry I saw it on an opens issue website thought it was for everybody.
Good luck on your project

**Comment by Davon95** [comment]
You're good man! And thanks, kick ass on your coding adventure.
